#!/usr/bin/env bash

# PUBLIC API
function join {
    local IFS="$1"
    shift
    echo "$*"
}

function in_array() {
    for i in "${@:2}"; do
        if [ "$i" == "$1" ]; then
            echo 1
        fi
    done
}
